//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppActs.Client.WebSite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{ 
	Email : ""admin@admin.com"", 
	Name : ""Admin"", 
	Active : true, 
	ForgotPasswordGuid : BinData(3,""AAAAAAAAAAAAAAAAAAAAAA==""),
	Password : ""0GGEm3kSzVXxOGwzBTbzBnvZMS9dIr2trFpnWCNG9Sa1y4JuVxMKQeJ97UMAkg7fxP10qdx2GIjsXPSalROyGib8+rkPhZD0v5wfcFFs5uzRScawSGftc2ttGf4ebhq51lggb8e5UCxnmBZpPkbfYob6HQCswmy34HW6VyIypSVwTdmDhNil+A=="",
	Guid : BinData(3,""veCD6XtL5kSLuYnh89PW+A=="") 
}              
                
            ")]
        public string StartupSystemUser {
            get {
                return ((string)(this["StartupSystemUser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n\t\t\t{\r\n\t\t\t\t{ Type : 5, Name: \'Android\' },\r\n\t\t\t\t{ Type : 4, Name: \'Blackberry\' }," +
            "\r\n\t\t\t\t{ Type : 2, Name: \'iOS\' },\r\n\t\t\t\t{ Type : 6, Name: \'WP7\' }\r\n\t\t\t}")]
        public string StartupSystemPlatform {
            get {
                return ((string)(this["StartupSystemPlatform"]));
            }
        }
    }
}
